# MATH 210 Introduction to Mathematical Computing

## February 5, 2018

1. Array functions (and methods)
2. Array indexing and slicing
3. Array stacking
4. Parametric plots
5. Examples

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## 1. Array functions

There are many [array functions](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#universal-functions) (besides the usual mathematical functions `exp`, `sin`, `cos`, etc.) we can use to compute with NumPy arrays. For example, we have `np.sum`, `np.mean`, `np.max`, `np.min`, etc.

To make demonstrating these functions more interesting, let's use NumPy's [random number generators](https://docs.scipy.org/doc/numpy/reference/routines.random.html#simple-random-data):

In [2]:
M = np.random.randint(0,10,size=(4,3))

In [3]:
print(M)

[[2 4 2]
 [2 1 1]
 [3 2 0]
 [0 6 2]]


Use the function `numpy.sum` to sum all the entries in the array:

In [4]:
np.sum(M)

25

We can also call the function using the dot syntax:

In [5]:
M.sum()

25

It is the same result. The first way is an example of functional programming. The second is an example of object-oriented programming.

The function `numpy.sum` also takes a keyword argument `axis` which determines along which dimension to compute the sum:

In [6]:
np.sum(M,axis=0) # Sum of the columns

array([ 7, 13,  5])

In [7]:
np.sum(M,axis=1) # Sum of the rows

array([8, 4, 5, 8])

Again, we can the dot syntax in a object-oriented style:

In [8]:
M.sum(axis=1)

array([8, 4, 5, 8])

Let's compute the mean of the rows and columns of `M`:

In [9]:
print(M)

[[2 4 2]
 [2 1 1]
 [3 2 0]
 [0 6 2]]


In [10]:
M.mean(axis=0)

array([ 1.75,  3.25,  1.25])

In [11]:
M.mean(axis=1)

array([ 2.66666667,  1.33333333,  1.66666667,  2.66666667])

Finally, let's compute the product along the columns of `M`:

In [12]:
M.prod(axis=0)

array([ 0, 48,  0])

## 2. Indexing and slicing

[Indexing and slicing](https://docs.scipy.org/doc/numpy/user/basics.indexing.html) refers to accessing entries or subarrays (called slices) of NumPy arrays. Let's create a random matrix and access its entries using square bracket syntax:

In [13]:
N = np.random.randint(-100,100,size=(3,7))
print(N)

[[ 57 -45  65 -15   1  11 -66]
 [-83  31  56 -67  93 -83   2]
 [-21 -68 -12 -38 -55 -28  36]]


Select the entry in row at index 2 and column at index 4:

In [14]:
N[2,4]

-55

Select the top left entry:

In [15]:
N[0,0]

57

Select the column at index 3:

In [16]:
c = N[:,3]

In [17]:
print(c)

[-15 -67 -38]


Slices of NumPy arrays are again NumPy arrays but possibly of a different dimension:

In [18]:
c.ndim

1

In [19]:
c.shape

(3,)

In [20]:
type(c)

numpy.ndarray

The variable `c` is assigned to a 1-dimensional NumPy array of length 3. If we want it to be a 2-dimsensional array which is 3 by 1, then we use the reshape array method:

In [21]:
C = c.reshape(3,1)

In [22]:
print(C)

[[-15]
 [-67]
 [-38]]


In [23]:
C.ndim

2

In [24]:
C.shape

(3, 1)

Let's create a 4 by 4 matrix and select the lower right 2 by 2 block:

In [25]:
P = np.random.randint(-50,50,size=(4,4))

In [26]:
print(P)

[[-49 -27 -39   6]
 [-36   7  14  33]
 [-35 -19 -35  -6]
 [-47  43  36  38]]


In [27]:
D = P[2:4,2:4]
print(D)

[[-35  -6]
 [ 36  38]]


## 3. Array stacking

We can [combine arrays](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html#joining-arrays) to create larger arrays:

In [28]:
A = np.ones((2,2))
B = 2*np.ones((2,2))
C = 3*np.ones((2,2))
D = 4*np.ones((2,2))

In [29]:
print(A)

[[ 1.  1.]
 [ 1.  1.]]


In [30]:
print(D)

[[ 4.  4.]
 [ 4.  4.]]


In [31]:
X1 = np.vstack([A,C])
X2 = np.vstack([B,D])
X = np.hstack([X1,X2])
print(X)

[[ 1.  1.  2.  2.]
 [ 1.  1.  2.  2.]
 [ 3.  3.  4.  4.]
 [ 3.  3.  4.  4.]]


Let's stack 1-dimensional arrays to create 2-dimensional arrays:

In [32]:
v1 = np.random.randint(0,10,10)
print(v1)
v2 = np.random.randint(0,10,10)
print(v2)

[4 3 6 1 1 7 3 3 8 2]
[1 9 1 0 1 0 6 0 4 7]


In [33]:
B = np.vstack([v1,v2])
print(B)

[[4 3 6 1 1 7 3 3 8 2]
 [1 9 1 0 1 0 6 0 4 7]]


Use the transpose to create a matrix with these vectors as the columns:

In [34]:
C = np.vstack([v1,v2]).T
print(C)

[[4 1]
 [3 9]
 [6 1]
 [1 0]
 [1 1]
 [7 0]
 [3 6]
 [3 0]
 [8 4]
 [2 7]]
